In [1]:
import pandas as pd
import numpy as np

In [2]:
us_finance = pd.read_csv(r"C:\Users\benso\Downloads\Data.Gov-FY25Q44.csv",sep=";",low_memory=False)
us_finance.head()

,Fiscal Year,Unique Identifier,Deal Number,Decision,Decision Date,Effective Date,Expiration Date,Brokered,Deal Cancelled,Country,...,Working Capital Delegated Authority,Approved/Declined Amount,Disbursed/Shipped Amount,Undisbursed Exposure Amount,Outstanding Exposure Amount,Small Business Authorized Amount,Woman Owned Authorized Amount,Minority Owned Authorized Amount,Loan Interest Rate,Multiyear Working Capital Extension
0,2007,08003048XA0002,AP003048AA,Approved,11/29/2006,NaN,12/15/2011,No,No,Private Export Funding Corp.,...,NaN,24500000.0,24500000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,2007,08003048XA0003,AP003048AA,Approved,11/29/2006,11/29/2006,12/15/2016,No,No,Private Export Funding Corp.,...,NaN,50000000.0,50000000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,2007,08003048XA0004,AP003048AA,Approved,8/16/2007,8/16/2007,9/15/2017,No,No,Private Export Funding Corp.,...,NaN,136250000.0,136250000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,2007,08064737XM0001,AP064737XM,Approved,9/21/2007,9/21/2007,7/31/2008,No,No,United States,...,Yes,2700000.0,2700000.0,0.0,0.0,2700000.0,0.0,2700000.0,NaN,NaN
4,2007,08069888XG0003,AP069888XG,Approved,11/24/2006,11/24/2006,01/01/2007,No,No,United States,...,Yes,233307.9,233307.9,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [3]:
us_finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52122 entries, 0 to 52121
Data columns (total 34 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Fiscal Year                            52122 non-null  int64
 1   Unique Identifier                      52122 non-null  object
 2   Deal Number                            52115 non-null  object
 3   Decision                               52122 non-null  object
 4   Decision Date                          52122 non-null  object
 5   Effective Date                         50871 non-null  object
 6   Expiration Date                        51435 non-null  object
 7   Brokered                               52122 non-null  object
 8   Deal Cancelled                         52122 non-null  object
 9   Country                                52122 non-null  object
 10  Program                                52122 non-null  object
 11  Policy Type                            42961 non-null  object
 12  Decision Authority                     52115 non-null  object
 13  Primary Export Product NAICS/SIC code  50616 non-null  object
 14  Product Description                    50616 non-null  object
 15  Term                                   52122 non-null  object
 16  Primary Applicant                      52107 non-null  object
 17  Primary Lender                         21504 non-null  object
 18  Primary Exporter                       51928 non-null  object
 19  Primary Exporter City                  50423 non-null  object
 20  Primary Exporter State Code            50423 non-null  object
 21  Primary Exporter State Name            50423 non-null  object
 22  Primary Borrower                       52120 non-null  object
 23  Primary Source of Repayment (PSOR)     52113 non-null  object
 24  Working Capital Delegated Authority    6100 non-null   object
 25  Approved/Declined Amount               52120 non-null  float64
 26  Disbursed/Shipped Amount               52120 non-null  float64
 27  Undisbursed Exposure Amount            52120 non-null  float64
 28  Outstanding Exposure Amount            52120 non-null  float64
 29  Small Business Authorized Amount       52120 non-null  float64
 30  Woman Owned Authorized Amount          52120 non-null  float64
 31  Minority Owned Authorized Amount       52120 non-null  float64
 32  Loan Interest Rate                     372 non-null    object
 33  Multiyear Working Capital Extension    251 non-null    object
dtypes: float64(7), int64(1), object(26)
memory usage: 13.5+ MB

In [4]:
us_finance.isnull().sum().sort_values(ascending=False)

Multiyear Working Capital Extension      51871
Loan Interest Rate                       51750
Working Capital Delegated Authority      46022
Primary Lender                           30618
Policy Type                               9161
Primary Exporter City                     1699
Primary Exporter State Name               1699
Primary Exporter State Code               1699
Primary Export Product NAICS/SIC code     1506
Product Description                       1506
Effective Date                            1251
Expiration Date                            687
Primary Exporter                           194
Primary Applicant                           15
Primary Source of Repayment (PSOR)           9
Decision Authority                           7
Deal Number                                  7
Small Business Authorized Amount             2
Woman Owned Authorized Amount                2
Minority Owned Authorized Amount             2
Approved/Declined Amount                     2
Outstanding Exposure Amount                  2
Undisbursed Exposure Amount                  2
Primary Borrower                             2
Disbursed/Shipped Amount                     2
Decision Date                                0
Decision                                     0
Unique Identifier                            0
Term                                         0
Program                                      0
Country                                      0
Deal Cancelled                               0
Brokered                                     0
Fiscal Year                                  0
dtype: int64

In [5]:
# Check what the raw value looks like before splitting
print(us_finance[us_finance['Loan Interest Rate'] == 'Tied Aid']['Loan Interest Rate'])

5622    Tied Aid
5623    Tied Aid
5624    Tied Aid
5625    Tied Aid
8580    Tied Aid
Name: Loan Interest Rate, dtype: object

In [6]:
us_finance.columns = us_finance.columns.str.strip()

In [7]:
us_finance.drop(columns=["Multiyear Working Capital Extension"], inplace=True)

In [8]:
us_finance.isnull().sum().sort_values(ascending=False)

Loan Interest Rate                       51750
Working Capital Delegated Authority      46022
Primary Lender                           30618
Policy Type                               9161
Primary Exporter State Name               1699
Primary Exporter State Code               1699
Primary Exporter City                     1699
Primary Export Product NAICS/SIC code     1506
Product Description                       1506
Effective Date                            1251
Expiration Date                            687
Primary Exporter                           194
Primary Applicant                           15
Primary Source of Repayment (PSOR)           9
Deal Number                                  7
Decision Authority                           7
Approved/Declined Amount                     2
Minority Owned Authorized Amount             2
Woman Owned Authorized Amount                2
Small Business Authorized Amount             2
Outstanding Exposure Amount                  2
Primary Borrower                             2
Undisbursed Exposure Amount                  2
Disbursed/Shipped Amount                     2
Unique Identifier                            0
Term                                         0
Country                                      0
Program                                      0
Decision                                     0
Decision Date                                0
Brokered                                     0
Deal Cancelled                               0
Fiscal Year                                  0
dtype: int64

In [9]:
us_finance.replace(["NA","N/A",""],np.nan,inplace=True)

In [10]:
us_finance.isnull().sum().sort_values(ascending=False)

Loan Interest Rate                       51750
Working Capital Delegated Authority      46022
Primary Lender                           30618
Policy Type                               9161
Primary Exporter State Name               1699
Primary Exporter State Code               1699
Primary Exporter City                     1699
Primary Export Product NAICS/SIC code     1506
Product Description                       1506
Effective Date                            1251
Expiration Date                            687
Primary Exporter                           194
Primary Applicant                           15
Primary Source of Repayment (PSOR)           9
Deal Number                                  7
Decision Authority                           7
Approved/Declined Amount                     2
Minority Owned Authorized Amount             2
Woman Owned Authorized Amount                2
Small Business Authorized Amount             2
Outstanding Exposure Amount                  2
Primary Borrower                             2
Undisbursed Exposure Amount                  2
Disbursed/Shipped Amount                     2
Unique Identifier                            0
Term                                         0
Country                                      0
Program                                      0
Decision                                     0
Decision Date                                0
Brokered                                     0
Deal Cancelled                               0
Fiscal Year                                  0
dtype: int64

In [11]:
print(us_finance.duplicated(subset=['Unique Identifier']).sum())

0

In [12]:
us_finance.head()

,Fiscal Year,Unique Identifier,Deal Number,Decision,Decision Date,Effective Date,Expiration Date,Brokered,Deal Cancelled,Country,...,Primary Source of Repayment (PSOR),Working Capital Delegated Authority,Approved/Declined Amount,Disbursed/Shipped Amount,Undisbursed Exposure Amount,Outstanding Exposure Amount,Small Business Authorized Amount,Woman Owned Authorized Amount,Minority Owned Authorized Amount,Loan Interest Rate
0,2007,08003048XA0002,AP003048AA,Approved,11/29/2006,NaN,12/15/2011,No,No,Private Export Funding Corp.,...,Various Us Companies,NaN,24500000.0,24500000.0,0.0,0.0,0.0,0.0,0.0,NaN
1,2007,08003048XA0003,AP003048AA,Approved,11/29/2006,11/29/2006,12/15/2016,No,No,Private Export Funding Corp.,...,Various Us Companies,NaN,50000000.0,50000000.0,0.0,0.0,0.0,0.0,0.0,NaN
2,2007,08003048XA0004,AP003048AA,Approved,8/16/2007,8/16/2007,9/15/2017,No,No,Private Export Funding Corp.,...,Various Us Companies,NaN,136250000.0,136250000.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2007,08064737XM0001,AP064737XM,Approved,9/21/2007,9/21/2007,7/31/2008,No,No,United States,...,American General Supplies,Yes,2700000.0,2700000.0,0.0,0.0,2700000.0,0.0,2700000.0,NaN
4,2007,08069888XG0003,AP069888XG,Approved,11/24/2006,11/24/2006,01/01/2007,No,No,United States,...,Kell-Strom Tool Co Inc,Yes,233307.9,233307.9,0.0,0.0,0.0,0.0,0.0,NaN

In [13]:
date_cols=['Decision Date','Effective Date','Expiration Date']
for cols in date_cols:
    us_finance[cols]=pd.to_datetime(us_finance[cols],errors='coerce')

In [14]:
us_finance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52122 entries, 0 to 52121
Data columns (total 33 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Fiscal Year                            52122 non-null  int64
 1   Unique Identifier                      52122 non-null  object
 2   Deal Number                            52115 non-null  object
 3   Decision                               52122 non-null  object
 4   Decision Date                          52122 non-null  datetime64[ns]
 5   Effective Date                         50871 non-null  datetime64[ns]
 6   Expiration Date                        51435 non-null  datetime64[ns]
 7   Brokered                               52122 non-null  object
 8   Deal Cancelled                         52122 non-null  object
 9   Country                                52122 non-null  object
 10  Program                                52122 non-null  object
 11  Policy Type                            42961 non-null  object
 12  Decision Authority                     52115 non-null  object
 13  Primary Export Product NAICS/SIC code  50616 non-null  object
 14  Product Description                    50616 non-null  object
 15  Term                                   52122 non-null  object
 16  Primary Applicant                      52107 non-null  object
 17  Primary Lender                         21504 non-null  object
 18  Primary Exporter                       51928 non-null  object
 19  Primary Exporter City                  50423 non-null  object
 20  Primary Exporter State Code            50423 non-null  object
 21  Primary Exporter State Name            50423 non-null  object
 22  Primary Borrower                       52120 non-null  object
 23  Primary Source of Repayment (PSOR)     52113 non-null  object
 24  Working Capital Delegated Authority    6100 non-null   object
 25  Approved/Declined Amount               52120 non-null  float64
 26  Disbursed/Shipped Amount               52120 non-null  float64
 27  Undisbursed Exposure Amount            52120 non-null  float64
 28  Outstanding Exposure Amount            52120 non-null  float64
 29  Small Business Authorized Amount       52120 non-null  float64
 30  Woman Owned Authorized Amount          52120 non-null  float64
 31  Minority Owned Authorized Amount       52120 non-null  float64
 32  Loan Interest Rate                     372 non-null    object
dtypes: datetime64[ns](3), float64(7), int64(1), object(22)
memory usage: 13.1+ MB

In [15]:
print(us_finance['Loan Interest Rate'].value_counts())

Loan Interest Rate
Undisbursed      40
Floating Rate    26
2.65             12
3.11             10
3.94              8
                 ..
2.5               1
3.282             1
2.06              1
1.83              1
5.36              1
Name: count, Length: 104, dtype: int64

In [16]:
us_finance['Loan Interest Rate(Numeric)']=pd.to_numeric(us_finance['Loan Interest Rate'],errors='coerce')
us_finance['Loan Interest Rate(Category)']=us_finance['Loan Interest Rate'].where(
    us_finance['Loan Interest Rate(Numeric)'].isna() & us_finance['Loan Interest Rate'].notna()
)
us_finance['Loan Interest Rate(Category)']=us_finance['Loan Interest Rate(Category)'].replace('Undisbursed',np.nan)
us_finance=us_finance.drop(columns=['Loan Interest Rate'])

In [17]:
us_finance

,Fiscal Year,Unique Identifier,Deal Number,Decision,Decision Date,Effective Date,Expiration Date,Brokered,Deal Cancelled,Country,...,Working Capital Delegated Authority,Approved/Declined Amount,Disbursed/Shipped Amount,Undisbursed Exposure Amount,Outstanding Exposure Amount,Small Business Authorized Amount,Woman Owned Authorized Amount,Minority Owned Authorized Amount,Loan Interest Rate(Numeric),Loan Interest Rate(Category)
0,2007,08003048XA0002,AP003048AA,Approved,2006-11-29,NaT,2011-12-15,No,No,Private Export Funding Corp.,...,NaN,24500000.0,24500000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,2007,08003048XA0003,AP003048AA,Approved,2006-11-29,2006-11-29,2016-12-15,No,No,Private Export Funding Corp.,...,NaN,50000000.0,50000000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,2007,08003048XA0004,AP003048AA,Approved,2007-08-16,2007-08-16,2017-09-15,No,No,Private Export Funding Corp.,...,NaN,136250000.0,136250000.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,2007,08064737XM0001,AP064737XM,Approved,2007-09-21,2007-09-21,2008-07-31,No,No,United States,...,Yes,2700000.0,2700000.0,0.0,0.0,2700000.0,0.0,2700000.0,NaN,NaN
4,2007,08069888XG0003,AP069888XG,Approved,2006-11-24,2006-11-24,2007-01-01,No,No,United States,...,Yes,233307.9,233307.9,0.0,0.0,0.0,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52117,2025,09787003ST1001,787003,Approved,2025-09-19,2025-11-15,2026-12-01,Yes,No,Mexico,...,NaN,98000.0,0.0,98000.0,0.0,98000.0,0.0,0.0,NaN,NaN
52118,2025,09787330ST1001,787330,Approved,2025-09-17,2025-11-01,2026-11-01,Yes,No,Costa Rica,...,NaN,45000.0,0.0,45000.0,0.0,45000.0,0.0,45000.0,NaN,NaN
52119,2025,09787377ST1001,787377,Approved,2025-09-24,2025-09-01,2026-09-01,Yes,No,Multiple - Countries,...,NaN,700000.0,0.0,700000.0,0.0,0.0,0.0,0.0,NaN,NaN
52120,2025,09787399ST1001,787399,Approved,2025-09-22,2025-10-01,2026-10-01,Yes,No,Canada,...,NaN,36000.0,0.0,36000.0,0.0,36000.0,36000.0,0.0,NaN,NaN
52121,2025,09787413ST1001,787413,Approved,2025-09-18,2025-09-01,2026-09-01,Yes,No,Australia,...,NaN,54000.0,0.0,54000.0,0.0,54000.0,0.0,0.0,NaN,NaN

In [18]:
us_finance.to_csv(
    r"C:\Users\benso\Documents\RFM_Project\us_finance.csv",
    index=False
)

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\benso\\Documents\\RFM_Project\\us_finance.csv'

In [ ]:
print(us_finance['Loan Interest Rate(Category)'].value_counts())

In [ ]:
# Check what the raw value looks like before splitting
print(us_finance[us_finance['Loan Interest Rate'] == 'Tied Aid']['Loan Interest Rate'])